<script lang="ts">
  import { page } from "$app/stores";
  import { onMount } from "svelte";
  import { PUBLIC_APIURL } from "$env/static/public";
  import Thickline from "$lib/icons/svgs/thickline.svelte";
  import Heading from "$lib/components/heading/Heading.svelte";
  import ShadowArrow from "$lib/icons/svgs/shadowArrow.svelte";
  import P from "$lib/components/paragraph/Paragraph.svelte";
  import Dropdown from "./dropdown.svelte";
  import Explore from "$lib/components/ui/explore/Explore.svelte";
  import YellowDot from "$lib/icons/svgs/yellowDot.svelte";
  import Boxview from "$lib/components/boxview/BoxView.svelte";
  import Pellete from "./boxView.svelte";
  import Downarrow from "$lib/icons/svgs/downarrow.svelte";
  import { slide } from "svelte/transition";
  import Flukerelaibility from "./flukerelaibility.svelte";
  import Sonotec from "./SonoTec.svelte";

  /** @type {import('./$types').PageData} */
  export let data;
  let showContent = false;
  interface name {
    title: string;
    text?: string;
  }
  const exploreData: name[] = [
    {
      title: "Explore the IPEC products from assetconditionminitoring.com",
      text: "Explore",
    },
  ];
  const data2: name[] = [
    {
      title: "Interested to know more?",
      text: "Let's Talk",
    },
  ];
  interface boxData {
    img?: string;
    title?: string;
    text?: string;
    list?: string[];
  }
  const datas: boxData[] = [
    {
      img: "/assets/img/ipec-img1.png",
      title: "PD Detector Pro – Next-Gen Handheld PD Testing",
      text: "Accurate, easy-to-use spot testing for MV/HV assets with advanced noise rejection, clear touchscreen analysis, and wide sensor compatibility.",
      list: [
        "Intuitive touchscreen interface for easy operation",
        "Advanced noise filtering for accurate PD detection in challenging environments",
        "Compatible with a wide range of PD sensors for versatile testing options",
      ],
    },
    {
      img: "/assets/img/ipec-img2.png",
      title:
        "PD Detector – On-line Partial Discharge Spot Testing for HV Assets",
      text: "The PD Detector is a portable, online PD spot tester designed for high-voltage (HV) assets.",
      list: [
        "Fast Substation Surveying.",
        "View PRPD (Phase-Resolved partial discharge) patterns directly on the device or mobile app for detailed PD diagnostics",
        "Accurately detects PD even in noisy environments through Advanced Noise Separation.",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_12}`,
      title: "PrecisePD",
      text: " PrecisePD® is an on-line Partial Discharge Spot Testing and Location System for Cables and Switchgear with advanced signal processing.",
      list: ["Sensitive PD detection in high noise environments"],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_14}`,
      title: "PD-SG1",
      text: " The PD-SG1 is a dual transducer Switchgear PD testing instrument. The unit detects PD signals generated by internal discharges…",
      list: [
        "Ultrasonic detection of surface PD activity, displayed on the LCD screen as dB reading",
      ],
    },
  ];
  const datas1: boxData[] = [
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_1}`,
      title: "ASM Permanent PD Monitor",
      text: "ASM is a permanent PD monitor for cables, switchgear, and other HV assets, configurable for multiple sensor channels.",
      list: [
        "PD sensors connect to HV network",
        "19” cabinet with customizable options",
        "Automatic data transfer to central base",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.section7_image}`,
      title: "ASM-Portable – Portable PD Monitor",
      text: "ASM-Portable is a portable PD monitor for cables, switchgear, and other HV assets, and forms part of IPEC’s on-line PD monitoring range.",
      list: [
        "Plots PD Peak, PD Count, Load, Asset Criticality, and analogues over time",
        "Any time period selectable",
        "Up to 8 channels selectable at one time",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.section6_image}`,
      title: "DeCIFer – PD Noise Cancelling",
      text: "There are several factors that affect the quality of On-line partial discharge detection including sensitivity of sensors, rate and…",
      list: [
        "Market leading tool for removing noise and identifying PD",
        "Use our years of experience to automate PD detectionc",
        "Ensure PD is found and false positives are kept to a minimum",
      ],
    },
  ];
  const datas2: boxData[] = [
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_11}`,
      title: "VDS – PD Detector Pro",
      text: " IPEC’s compact VDS sensor is used to measure the presence and severity of partial discharge (PD) activity within air- or gas-insulated…",
      list: [
        "Detects high frequency transience emitted by PD within GIS and AIS.",
        "The sensor connects to LV ports on the switchgear, allowing consistent, per phase measurements.",
        "Easy to use and housed in a lightweight casing that can be magnetically mounted to the asset.",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_3}`,
      title: "CC-TEV",
      text: " The CC-TEV Capacitive Coupler detects TEVs as they pass over the cladding of the high voltage plant. Fast output signals are recorded by th…",
      list: [
        "Detects TEVs as they pass over the cladding of the high voltage plant.",
        "Fast output signals are recorded by the ASM, PrecisePD or PD-SG1 systems.",
        "Sensor is encased in a durable PVC sleeve for added protection.",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_2}`,
      title: "AA-Ultrasonic",
      text: " The AA Ultrasonic acoustic probe is designed for use on air insulated terminations where a clear sound path between the electrically…",
      list: [
        "Extremely sensitive and can detect activity below 10pC.",
        "Magnetic base to allow coupling to steel enclosures.",
        "Swivel head so the detecting sensor can be aimed directly at the HV point. This is a feature.",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_13}`,
      title: "HFCT",
      text: "  The HFCT is a high frequency current transformer designed specifically for picking up partial discharge signals, predominantly i…",
      list: [
        "Ideal for all earth and neutral PD monitoring applications.",
        "Designed specifically for picking up partial discharge signals.",
        "Constructed with an aluminium body to provide RF shielding.",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_9}`,
      title: "UHF",
      text: "  IPEC’s UHF (Ultra High Frequency) sensors are used to detect PD in EHV cable terminations, GIS (Gas Insulated Switchgear). The sensors...",
      list: [
        "Used to detect PD in EHV cable terminations, GIS (Gas Insulated Switchgear)",
        "Sensors pick up signals in the UHF range (200MHz–2.5GHz)",
        "Ensure more accurate PD detection",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_7}`,
      title: "Noise Gating",
      text: "When PD signals occur within GIS assets, the Ultra-High Frequency signal, which is emitted, if of significant level, may be detected by...",
      list: [
        "Signals can be isolated and removed from the other sensors to ensure a clearer PD location",
        "Isolate any spurious background noise signals in the UHF frequency range",
        "Constructed with an aluminium body to provide RF shielding.",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_5}`,
      title: "Environment Sensor",
      text: " The temperature and humidity sensor generates frequency modulated signals on two output channels, one corresponding to t...",
      list: [
        "Generates frequency modulated signals on two output channels",
        "Sensor should be mounted on the wall at an appropriate position",
        "Measure substation environmental conditions",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_8}`,
      title: "Parabolic Reflector",
      text: " Parabolic Reflector is an ultrasonic sensor for use when detecting partial discharge activity on exposed insulating surfaces. The reflector...",
      list: [
        "Ultrasonic sensor for use when detecting partial discharge activity on exposed insulating surfaces",
        "Generate an audible output according to the level of activity detected",
        "Reflector increases the sensitivity of the sensor allowing detection to be effective at up to 100m",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_6}`,
      title: "Flexible AA Probe",
      text: "  Flexible AA Ultrasonic Probe is an accessory to IPEC’s Partial Discharge Spot Testing instruments. It allows the user to complete a...",
      list: [
        "Complete a thorough inspection of electrical assets",
        "User-friendly device which has been designed ergonomically",
        "Detect Surface Tracking in difficult to reach locations",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_4}`,
      title: "Contact AA",
      text: " The Contact Acoustic Sensor is mainly used for oil filled transformers, circuit breakers and other plant. Its main function is to detect...",
      list: [
        "Mainly used for oil filled transformers, circuit breakers and other plant",
        "Detects high frequency signals caused by partial discharge inside the switchgear",
        "Can also be used as an accessory with IPEC PD Spot Testers",
      ],
    },
    {
      img: `${PUBLIC_APIURL}/assets/${data.productDetails.image_ipec_10}`,
      title: " UHF-E",
      text: "The embedded UHF PD sensor is designed for specific applications and can be positioned in a cable termination box or at other locations...",
      list: [
        "Detects ultra high frequency electromagnetic waves emitted by PD",
        "The internal placement shields the sensor from ambient RF noise, improving measurement accuracy and reliability.",
        "Designed to capture a broad range of UHF frequencies, enabling detection of small, fast PD pulses that external sensors might miss.",
      ],
    },
  ];

  let pageComponent: any;
  onMount(() => {
    pageComponent = $page.params.id;
    console.log("The component has mounted!", $page.params.id);
    // Perform actions that need to happen after the component is added to the DOM
  });
</script>

{#if data.productDetails.translations[0].title.includes("IPEC")}
  <section>
    <div class="pt-24 sm:pt-28 lg:pt-28">
      <div class="flex items-center justify-center relative">
        <img
          src={`${PUBLIC_APIURL}/assets/${data.productDetails.banner_image}`}
          alt="IPEC"
          class="w-full h-[300px] md:h-[300px] lg:h-[450px] object-cover"
        />
        <div class="absolute inset-0 bg-black opacity-40"></div>
        <div class="absolute left-[2%] w-fit h-auto">
          <div class="flex items-center gap-1 h-[50px] md:h-[70px]">
            <Thickline data="w-[1.5rem] md:w-[3rem] h-20px" />
            <Heading size="h2bold2" className=" font-bold text-white ">
              IPEC
            </Heading>
          </div>
        </div>

        <div
          class="absolute right-0 bottom-0 z-20 w-[223px] md:w-[400px] xl:w-[620px] lg:w-[500px] md:h-[80px] h-16 sm:h-24"
        >
          <svg
            class="absolute inset-0 w-full h-full"
            viewBox="0 0 620 96"
            preserveAspectRatio="none"
          >
            <path
              d="M0,96 L60,20 Q80,0 120,0 L620,0 L620,96 Z"
              fill="#C9D400"
            />
          </svg>

          <div
            class="relative z-10 flex items-center justify-center w-full h-full px-4"
          >
            <div class="flex items-center">
              <span
                class="text-white font-bold"
                style="font-size: clamp(1rem, 3vw, 2rem);"
              >
                Lets Talk
              </span>
              <span class="md:pt-2 pt-1">
                <ShadowArrow data="md:h-8 md:w-5 h-5 w-5 ml-2 md:ml-4" />
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="mt-16">
    <div class="container mx-auto md:px-[55px] mt-10">
      <div class="flex justify-start">
        <div class="h-[30px] md:h-[50px] w-[50px] md:w-[80px]">
          <img
            src="/assets/logo/ipec-logo.png"
            alt="IPEC Logo"
            class="w-full h-full object-contain"
          />
        </div>
      </div>
    </div>
  </section>

  <section class="mt-10">
    <div class="container mx-auto md:px-[55px]">
      <P size="texts18" className="text-gray-700  text-justify leading-relaxed">
        At AssetConditionMonitoring.com, we are proud to be the authorized
        distributor of <b>IPEC</b>, a global leader in online
        <b>Partial Discharge (PD) testing and monitoring solutions</b>, across
        the Middle East. Since over 80% of electrical asset failures are caused
        by insulation breakdown, <b>early detection is crucial.</b>
      </P>
      <P
        size="texts18"
        className="text-gray-700  text-justify leading-relaxed "
      >
        At AssetConditionMonitoring.com, we provide <b
          >IPEC’s cutting-edge PD monitoring solutions</b
        >, trusted globally for their accuracy, reliability, and performance in
        identifying insulation issues before they lead to costly failures.
      </P>
      <P
        size="texts18"
        className="text-gray-700  text-justify leading-relaxed mt-5"
      >
        IPEC develops industry-leading systems for detecting and monitoring
        partial discharge in <b>MV</b> and
        <b> HV cables,switchgear, and accessories.</b> From compact handheld testers
        with intuitive PD activity displays to sophisticated online systems that
        continuously record and analyze data, IPEC offers a comprehensive range of
        tools to assess insulation conditions and reduce the risk of unplanned outages.
      </P>
    </div>
  </section>

  <section>
    <div class="container mx-auto md:px-[55px]">
      <div class="flex flex-col lg:flex-row gap-6 justify-between mt-10">
        <div class="w-full lg:w-3/5 space-y-4">
          <Heading size="headingS25" className="font-bold text-[#0B60B0] mb-6">
            IPEC Partial Discharge Monitoring – Available Through
            AssetConditionMonitoring.com
          </Heading>

          <div
            class="w-[55%] sm:w-[55%] md:w-[45%] rounded-xl mx-auto lg:hidden"
          >
            <img
              src="/assets/img/underground-cables-ipec.png"
              alt="Underground cables IPEC"
              class="w-full h-auto md:h-[258px] object-cover rounded-xl"
            />
          </div>

          <P
            size="texts18"
            className="text-gray-700 text-justify leading-relaxed"
          >
            With decades of experience in the field and a commitment to
            international quality standards, IPEC’s solutions are designed to
            enhance operational safety, asset reliability, and maintenance
            planning. As an experienced and premier distributor in the region,
            AssetConditionMonitoring.com is your trusted partner for delivering
            IPEC’s cutting-edge PD technology. Whether you need spot-testing
            equipment or full-scale monitoring systems, we provide tailored
            solutions to meet your asset condition monitoring requirements
            across the Middle East.
          </P>
        </div>
        <div
          class="hidden lg:block w-[80%] sm:w-[80%] md:w-[60%] lg:w-2/5 rounded-xl mx-auto lg:mx-0"
        >
          <img
            src="/assets/img/underground-cables-ipec.png"
            alt="Underground cables IPEC"
            class="w-full h-auto md:h-[300px] lg:h-[350px] object-cover rounded-xl"
          />
        </div>
      </div>
    </div>
  </section>

  <section class="mt-16">
    <Explore name={exploreData} data={`/${data.langParam}/contactus`} />
  </section>

  <section class="mt-16">
    <div class="container mx-auto md:px-[55px]">
      <P size="texts18" className="text-gray-700  text-justify leading-relaxed">
        As an authorized distributor in the Middle East, we offer IPEC’s full
        range of latest PD products, including Portable Switchgear PD Testing
        Instruments, Cable PD Testing Systems, Permanent PD Monitoring Solutions
        for MV, HV, and EHV systems, and A comprehensive selection of PD
        Sensors.
      </P>
      <P
        size="texts18"
        className="text-gray-700 mt-3 text-justify leading-relaxed "
      >
        These advanced tools are designed to support utilities, industrial
        plants, and service providers in detecting insulation issues early,
        improving asset reliability, and reducing downtime. Whether for routine
        maintenance or continuous monitoring, we provide the perfect solution to
        meet your operational needs.
      </P>
    </div>
  </section>

  <section class="mt-24">
    <div class="container mx-auto md:px-[55px] flex justify-center">
      <div
        class="border border-[#0B60B0] rounded-full text-center max-w-fit px-3 md:px-px-10 lg:px-16 py-5 mx-auto"
      >
        <span
          class="font-bold text-[#1E3A8A] text-sm sm:text-base md:text-lg lg:text-[25px] break-words"
        >
          PD Instruments / Spot Testers
        </span>
      </div>
    </div>
  </section>

  <Pellete {datas} attribute="object-top" />

  <section class="mt-20">
    <div class=" z-0">
      <div class="container mx-auto md:px-[55px] lg:pt-16">
        <div class="flex justify-center">
          <div
            class="border border-[#0B60B0] rounded-full text-center max-w-fit px-3 md:px-px-10 lg:px-16 py-5 mx-auto"
          >
            <span
              class="font-bold text-[#1E3A8A] text-sm sm:text-base md:text-lg lg:text-[25px] break-words"
            >
              PD Monitoring systems
            </span>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section
    class="h-fit
"
  >
    <Pellete
      datas={datas1}
      attribute="object-cover object-top lg:object-cover md:object-cover md:max-h-[400px] lg:max-h-none "
    />
  </section>

  {#if showContent}
    <section class="mt-4 p-4 md:p-5 rounded overflow-hidden mb-5">
      <div class="container mx-auto px-4 md:px-8 lg:px-[55px]">
        <div class="flex justify-center mb-8 lg:mb-16">
          <div
            class="border border-[#0B60B0] rounded-full px-6 md:px-10 lg:px-16 py-4 md:py-5"
          >
            <span
              class="font-bold text-[#1E3A8A] text-sm sm:text-base md:text-lg lg:text-[25px] whitespace-nowrap"
            >
              PD Sensors
            </span>
          </div>
        </div>

        <!-- Assuming Pellete is your component name -->
      </div>
      <Pellete datas={datas2} attribute="object-cover" />
    </section>
  {/if}
  <section class="mt-10">
    <div class="flex items-center gap-2 mx-10">
      <span class="flex-grow border-t border-gray-400"></span>

      <span class="flex flex-col justify-center items-center cursor-pointer">
        <button
          class="whitespace-nowrap px-4 py-2 text-[#0B60B0] font-semibold rounded"
          on:click={() => (showContent = !showContent)}
        >
          {showContent ? "View Less" : "View More"}
        </button>
        <Downarrow />
      </span>

      <span class="flex-grow border-t border-gray-400"></span>
    </div>
  </section>

  <section class="mt-14 bg-[#F7F7F7] h-fit">
    <div class="pt-10 container mx-auto md:px-[55px] pb-10">
      <Heading
        size="bannerMaih1"
        className=" font-bold text-center text-[#2F2F2F] mt-7"
      >
        Get IPEC PD Testing Products at <span class=""
          >AssetConditionMonitoring.com</span
        >
      </Heading>
      <P
        size="texts18"
        className="text-gray-700 text-left mt-4 leading-relaxed px-4 md:px-0"
      >
        AssetConditionMonitoring.com is proud to represent IPEC, a specialist in
        the design and manufacture of partial discharge (PD) monitoring and
        testing solutions for the power industry.
      </P>
      <div class="mt-16 mb-20">
        <Explore name={data2} data={`/${data.langParam}/contactus`} />
      </div>
    </div>
  </section>
{/if}

{#if data.productDetails.translations[0].title.includes("Fluke")}
  <Flukerelaibility {data} />
{/if}

{#if data.productDetails.translations[0].title.includes("SONOTEC")}
  <Sonotec {data} />
{/if}
