import { practices } from "./earthPitTesting";

interface tables {
  title: string;
  description: string;
  descriptiontxt: string;
  typicalLocation: string;
  typicalLocationtxt: string;
  cause: string;
  causetxt: string;
}
export const tables: tables[] = [
  {
    title: "Corona Discharge",
    description: "Description",
    descriptiontxt:
      "Discharge in gas (usually air) around conductors or sharp edges",
    typicalLocation: "Typical Location",
    typicalLocationtxt: `Overhead lines, bushings`,

    cause: "Cause",
    causetxt: `High electric field at conductor edges`,
  },
  {
    title: "Surface Discharge",
    description: "Description",
    descriptiontxt: "Discharge along the surface of insulation",
    typicalLocation: "Typical Location",
    typicalLocationtxt: `Insulators, cable terminations`,

    cause: "Cause",
    causetxt: `Contamination, moisture on insulation`,
  },
  {
    title: "Internal (Void) Discharge",
    description: "Description",
    descriptiontxt:
      "Discharge within voids or air pockets inside solid or liquid insulation",
    typicalLocation: "Typical Location",
    typicalLocationtxt: `Solid insulation in cables, transformers`,

    cause: "Cause",
    causetxt: `Voids from aging or manufacturing defects`,
  },
  {
    title: "Tracking Discharge",
    description: "Description",
    descriptiontxt: "Surface discharge forming a carbon path",
    typicalLocation: "Typical Location",
    typicalLocationtxt: `Polluted/damp insulation surfaces  `,

    cause: "Cause",
    causetxt: `Repeated discharges leading to conductive path`,
  },
  {
    title: "Treeing Discharge",
    description: "Description",
    descriptiontxt: "Branch-like discharges progressing through insulation",
    typicalLocation: "Typical Location",
    typicalLocationtxt: `Solid polymer or oil-impregnated insulation`,
    cause: "Cause",
    causetxt: `Long-term electrical stress and degradation`,
  },
  {
    title: "Floating Electrode Discharge",
    description: "Description",
    descriptiontxt:
      "Discharge involving an ungrounded metal part inside insulation system",
    typicalLocation: "Typical Location",
    typicalLocationtxt: `Switchgear, transformers`,
    cause: "Cause",
    causetxt: `Capacitive coupling to a free-floating conductor`,
  },
];

interface name {
  title: string;
  text?: string;
}
export const name: name[] = [
  {
    title: " Concerned about insulation health? schedule a pd test today.",
    text: "Connect now",
  },
];

interface properties {
  title: string;
  text: string;
}
export const property: properties[] = [
  {
    title: "Ultrasonic Detection",
    text: "Detects corona PD through high-frequency acoustic signals.",
  },
  {
    title: "TEV (Transient Earth Voltage)",
    text: "Ideal for internal PD detection in metal-clad equipment like switchgear.",
  },
  {
    title: "UHF Monitoring",
    text: " A non-contact method for PD signals in Gas Insulated Switchgear and terminations.",
  },
  {
    title: "HFCT/RFCT Sensors",
    text: "Enable online partial discharge testing on energized cables using current transformer",
  },
];

interface points {
  title: string;
  detects: string;
  howitworks: string;
  usecase?: string;
}
export const points: points[] = [
  {
    title: "Ultrasonic Detection",
    detects: "Detects: Corona and surface discharges.",
    howitworks:
      "How it Works: Captures high-frequency acoustic emissions generated by PD.",
    usecase:
      "Use Case: Effective in open-air systems and accessible insulation surfaces.",
  },
  {
    title: " Transient Earth Voltage (TEV) Detection",
    detects: "Detects: Internal discharges in metal-clad switchgear.",
    howitworks:
      "How it Works: Measures high-frequency voltage pulses on metal surfaces caused by PD activity.",
  },
  {
    title: "Ultra High Frequency (UHF) Detection",
    detects: "Detects: Electromagnetic emissions from PD.",
    howitworks:
      "How it Works: Uses UHF antennas to pick up signals; ideal for enclosed systems.",
    usecase: "Use Case: Common in Gas Insulated Switchgear (GIS).",
  },
  {
    title:
      " High-Frequency Current Transformer (HFCT) / Radio Frequency Current Transformer (RFCT)",
    detects: "Detects: PD pulses in cables and grounded components",
    howitworks:
      "How it Works: Measures high-frequency current traveling through grounding conductors.",
    usecase: "Use Case: Suitable for online cable PD testing.",
  },
  {
    title: " Optical Detection",
    detects: "Detects: Light emissions from PD",
    howitworks:
      "How it Works: Uses photodetectors or cameras sensitive to visible or UV light.",
    usecase: "Use Case: Lab environments and enclosed visual PD monitoring.",
  },
  {
    title: "Electrical Detection (Conventional Method)",
    detects: "Detects: PD pulses using capacitive or inductive couplers.",
    howitworks:
      "How it Works: Measures voltage/current signals associated with PD using oscilloscopes or PD detectors.",
    usecase:
      "Use Case: Standard in lab and field tests, both offline and online.",
  },
];

interface standards {
  title: string;
  bullet1?: string;
  bullet2?: string;
  bullet3?: string;
  bullet4?: string;
}
export const standards: standards[] = [
  {
    title:
      "IEC 60270 – High-voltage test techniques – Partial discharge measurements",
    bullet1: "Primary global standard for PD testing.",
    bullet2:
      "Specifies methods to measure apparent charge and evaluate PD activity.",
    bullet3:
      "Applicable to switchgear, transformers, cables, and rotating machines.",
  },
  {
    title: `IEC 60034-27 / 60034-27-2 – Rotating electrical machines – PD testing
`,
    bullet1: `Focuses on PD detection in motors and generators, both offline and online.
`,
  },
  {
    title:
      "IEC 62478 – PD detection using electromagnetic and acoustic emission methods",
    bullet1: `Covers non-conventional PD detection techniques such as UHF, TEV, and ultrasonic methods.
`,
  },
  {
    title:
      "IEC 61869-15 – Instrument Transformers – PD performance requirements",
    bullet1: `Relates to the PD performance of voltage and current transformers.`,
  },
  {
    title:
      "IEEE 400 / 400.3 – Guide for field testing and evaluation of shielded power cable systems",
    bullet1: `Includes PD testing techniques for medium- and high-voltage cable systems.`,
  },
  {
    title:
      "IEEE 1434 – Guide for Partial Discharge Measurement in AC Electric Machinery",
    bullet1: `Covers PD testing for motors and generators.`,
  },
];

interface bulletsSentence {
  title?: string;
  paragraph?: string;
  text?: string;
  bullets?: string[];
}
export  const bulletins: bulletsSentence[] = [
    {
      title: `  What is the principle of partial discharge?`,
      paragraph: ` Partial discharge occurs when a localized electrical breakdown happens in
      a small part of the insulation system, but does not completely bridge the
      electrodes. It typically arises in defects such as voids, cracks, gas
      pockets, or along contaminated surfaces in high-voltage equipment. When
      the electric field stress in a localized area exceeds the dielectric
      strength of the insulating material (especially in gas-filled voids or
      interfaces), a small discharge happens—releasing energy in the form of:`,
      text: `This localized breakdown damages the insulation over time, eventually leading to full dielectric failure if left undetected.`,
      bullets: [
        "Light",
        " Heat",
        "Sound (ultrasonic)",
        "Electromagnetic radiation",
      ],
    },
  ];
export  const bulletins2: bulletsSentence[] = [
    {
      title: `Where It Happens:`,
      bullets: [
        "Voids in solid insulation",
        " Air gaps in cable terminations or joints",
        "Surface contamination on bushings or insulators",
        "Insulation interfaces in switchgear and transformers",
      ],
       text: `Monitoring and detecting PD is critical because it is often an early warning sign of insulation degradation and potential failure.`,
    },
  ];