export interface cardMain {
  cardHeader: string;
  cardPara?: string;
}
export interface cardData {
  cardNo: string;
  cardtitle: string;
  cardText?: string;
  cardText2?: string;
  bullet?: points[];
}
interface points {
  b1?: string;
  b1text?: string;
  b2?: string;
  b2text?: string;
  b3?: string;
  b3text?: string;
  b4?: string;
  b4text?: string;
  b5?: string;
  b5text?: string;
  b6?: string;
  b6text?: string;
  b7?: string;
  b7text?: string;
  b8?: string;
  b8text?: string;
}
export const pDMMain: cardMain[] = [
  {
    cardHeader:
      "Steps in Offline PD Measurement",
  },
];

export const pDMData: cardData[] = [
  {
    cardNo: "01",
    cardtitle: " Site Planning & Shutdown",
    bullet: [
      {
        b1: "Our engineers coordinate with your team to plan the required equipment shutdown.",
        b2: "A safe test setup is established, ensuring minimal disruption to operations.",
      }
    ],
  },
  {
    cardNo: "02",
    cardtitle: "PD Measurement",
    bullet: [
      {
        b1: "Using advanced IPEC offline PD testing equipment, we apply voltage to the de-energized asset.",
        b2: "Partial discharge activity is measured across the insulation system, pinpointing weaknesses or defects.",
      }
    ],
  },
  {
    cardNo: "03",
    cardtitle: "Preliminary Results",
   bullet: [
      {
        b1: "Immediate insights are shared onsite, enabling quick decision-making and faster return to service.",
        
      }
    ],
  },
  {
    cardNo: "04",
    cardtitle: "Detailed Reporting",
     bullet: [
      {
        b1: "A comprehensive PD test report is issued, highlighting test results, asset condition, and recommended corrective actions.",
        
      }
    ],
  },
];

export const pDMFaqs = [
  {
    q: " What is offline PD testing?",
    a: ` Offline Partial Discharge (PD) testing is performed when electrical equipment is de-energized and connected to a controlled power source. It helps detect insulation defects and weak points before the equipment is put back into service.
`,
  },
  {
    q: " How is partial discharge measured?",
    a: " Partial discharge is measured using specialized sensors and detectors that capture electrical pulses or acoustic signals generated by insulation defects. The readings are quantified in picoCoulombs (pC) to indicate discharge magnitude.",
  },
  {
    q: "What does the PD test result indicate?",
    a: " The PD test result reveals the presence, severity, and location of insulation weaknesses. High or localized PD activity often indicates potential faults that could lead to equipment failure if not addressed.",
  },
  {
    q: " What is the acceptable value for partial discharge?",
    a: " Acceptable PD values vary depending on equipment type and standards, but generally, values below 10 pC to 100 pC are considered safe. Higher levels may require closer monitoring or corrective maintenance.",
  },
 
  
];

interface bulletsSentence {
  title?: string;
  paragraph?: string;
  text?: string;
  bullets?: string[];
}


interface navitems {
  href: string;
  text: string;
}
export const pDM: navitems[] = [
  { href: "#what-is", text: "What Is Offline PDM?" },
  { href: "#benefits", text: "Benefits" },
  { href: "#why-choose-us", text: "Why Choose Us" },
  { href: "#faqs", text: "FAQS" },
];