 interface cardData {
  cardNo: string;
  cardtitle: string;
  cardText?: string;
  cardText2?: string;
  bullet?: points[];
}
interface points {
  b1?: string;
  b1text?: string;
  b2?: string;
  b2text?: string;
  b3?: string;
  b3text?: string;
  b4?: string;
  b4text?: string;
  b5?: string;
  b5text?: string;
  b6?: string;
  b6text?: string;
  b7?: string;
  b7text?: string;
  b8?: string;
  b8text?: string;
}
 interface cardMain {
  cardHeader: string;
  cardPara: string;
}

export const steamCardMain: cardMain[] = [
  {
    cardHeader: "Steam Trap Inspection Procedure",
    cardPara: `Steam Trap Testing Procedure is a meticulous process that needs to be done properly, requiring attention to details, accurate measurements, and a deep understanding of the performance of different types of traps under specific conditions. At assetconditionmonitoring.com, our experienced engineers handle these processes effortlessly. We follow a systematic, phased approach using advanced calibrated tools and trained professionals to ensure that even the smallest fault is not overlooked. Here is a breakdown of how we do the all-inclusive tra[p inspection procedure:
`,
  },
];

export const steamCardData: cardData[] = [
  {
    cardNo: "01",
    cardtitle: " Preparation and Visual Inspection",
    cardText: `Initial preparation is done where the steam traps are identified in the system and the necessary tools are gathered. After which, a visual examination of the steam trap components, including the trap body, valve mechanisms, piping, and insulations, is done. This reveals the evident damages such as leaks, physical wear, corrosion, etc. The general condition of the steam trap could be understood at this stage.
`,
  },
  {
    cardNo: "02",
    cardtitle: " Measurement and testing",
    cardText: `Using Specialised tools such as ultrasonic or acoustic equipment, along with temperature sensors, the trap function is tested (cycling, continuous flow, or failure sounds). General parameters such as steam and condensate temperatures, pressure differentials, and unusual flow behavior are measured.  These data provide conclusive insights into the efficiency of the steam trap.

`,
  },
  {
    cardNo: "03",
    cardtitle: "Operational Testing and Trap Condition Assessment",
    cardText: `The functional tests evaluate the steam trap's performance against expectations. Operators manually open and close the trap to check response time and ensure proper sealing of the valve mechanism. The operational testing identifies faulty traps missed during the initial inspection. The trap condition is also assessed, where traps are categorised as working, leaking, blocked, or blown. The trap type is then verified, their working conditions are analysed, and test results are recorded.

`,
  },
  {
    cardNo: "04",
    cardtitle: "Repair or replacement",
    cardText: `The defective steam traps are repaired by replacing gaskets and seals if the issue is non-consequential; if the damage is severe, the steam trap is replaced with a new unit.

`,
  },
  {
    cardNo: "05",
    cardtitle: "Documentation and reporting",
    cardText: `The findings, test results, measurements, and documentation of repairs or replacements are properly recorded and verified for future use. The condition of the steam trap, along with any recommendations or actions taken, is documented for future reference and maintenance schedules. This information is essential for planning repair schedules, determining spare part requirements, and facilitating system upgrades.

`,
  },
];

interface properties {
  title: string;
  text: string;
  bullets?: string[];
}
export const steamProperty: properties[] = [
  {
    title: "Device Setup",
    text: "Handheld ultrasonic detectors with a contact probe or clamp-on sensor are used. This is calibrated and set to the appropriate frequency range for steam systems.",
  },
  {
    title: "Contact with Trap",
    text: " The probe is placed directly on the body or piping near the steam trap. The device listens to the sound waves generated by the trap operation.",
  },
  {
    title: "Listening and Interpreting",
    text: " Operators hear real-time sounds through headphones and view signal patterns on the device screen. A properly working trap has a characteristic opening/closing (cycling)     sound.",
    bullets:[
      " A blown trap shows continuous flow (high-frequency hissing).",
      "A blocked trap shows little to no sound differences.",
      "A leaking trap has inconsistent noise with minor flow, even when closed."
    ]
  },
  {
    title: "Comparison and Analysis",
    text: " The sound pattern is compared to baseline readings to evaluate the performance. Technicians combine this with the temperature or pressure readings for precise assessment.",
  },
];

interface name {
  title: string;
  text?: string;
}
export const name: name[] = [
  {
    title: "Suspect steam loss? get your steam traps inspected by our expert.",
    text: "Call now!",
  },
];

export const steamFaqs = [
  {
    q: "How do you test steam traps?",
    a: " Steam traps are tested using a combination of tools like ultrasonic detectors, temperature sensors, and sometimes pressure gauges to check for efficient operation, leakage, or blockage. Ultrasound tools help detect high-frequency sounds indicating trap activity or failure. Inlet and outlet temperature difference lines are also measured to confirm trap performance.",
  },
  {
    q: "How do you know if a steam trap is bad?",
    a: "A steam trap is considered bad if it leaks live steam, fails to open, or stays stuck open or closed. Unusual temperature readings, continuous noise (indicating leakage), or zero discharge can signal a problem. Visual signs of corrosion, vibration, or water hammer also suggest failures.",
  },
  {
    q: "What is the purpose of a steam trap testing station?",
    a: " A testing station is set up to monitor and evaluate the performance of steam traps under controlled or real conditions. It helps detect faulty traps without disrupting the system, improving maintenance planning. The station allows repeated and reliable testing of multiple trap types and models.",
  },
  {
    q: "What tool is used to test steam traps?",
    a: "The most common tools include ultrasonic testers like SONAPHONE, temperature guns, and steam trap analyzers. These devices detect sound waves, temperature differences, and flow behavior to assess trap condition. Some tools combine sound and heat sensors for more precise diagnosis. Advanced systems also log data for reporting and maintenance tracking.",
  },
];

interface navitems {
  href: string;
  text: string;
}
export const steamTrapitems: navitems[] = [
  { href: "#what-is", text: "What is Steam Trap Testing? " },
  { href: "#procedure-of-steam-trap", text: "Procedure of Steam Trap Testing" },
  { href: "#ultrasound-testing-in-steamtrap", text: "Ultrasound Testing in Steam Trap" },
];